version: '3.9'

services:
  node-frontend:
    container_name: node-frontend
    # depends_on:
    #   - mssql-db
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    build./
    volumes:
      - ./:/workspace:cached

