version: '3.8'

services:
  aw-idem-api:
    container_name: aw-idem-api
    user: node
    tty: true
    ports:
      - "8080:8080"
    build: 
      context: ../
      dockerfile: ./.devcontainer/Dockerfile

networks:
  default:
    name: aw-idem_common_network
